# Generated by Django 5.0.7 on 2024-11-14 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0009_alter_beveragestock_beverage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('customer_name', models.CharField(max_length=250)),
                ('cash', models.IntegerField(default=0)),
                ('momo', models.IntegerField(default=0)),
                ('order_type', models.CharField(choices=[('1', 'Dine-in'), ('2', 'Online'), ('3', 'Takeaway')], max_length=50)),
                ('date_time', models.CharField(max_length=250)),
                ('comment', models.CharField(max_length=500)),
                ('sold_date', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_nbr', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('total_meal', models.IntegerField(default=0)),
                ('sold_date', models.DateField(auto_now=True)),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_orders', to='product.meal')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_meals', to='service.order')),
            ],
        ),
        migrations.CreateModel(
            name='BeverageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_qty', models.IntegerField(default=0)),
                ('left_qty', models.IntegerField(default=0)),
                ('sold_qty', models.IntegerField(blank=True, default=0)),
                ('price', models.IntegerField(default=0)),
                ('total_beverage', models.IntegerField(default=0)),
                ('sold_date', models.DateField(auto_now=True)),
                ('beverage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beverage_orders', to='product.beverage')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_beverages', to='service.order')),
            ],
        ),
        migrations.CreateModel(
            name='TeaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('total_tea', models.IntegerField(default=0)),
                ('sold_date', models.DateField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_teas', to='service.order')),
                ('tea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tea_orders', to='product.tea')),
            ],
        ),
    ]
