# Generated by Django 5.0.7 on 2024-11-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_beveragestock_beverage'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeverageOrderTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.IntegerField(blank=True, default=0)),
                ('tot_amount', models.IntegerField(blank=True, default=0)),
                ('tot_qty', models.IntegerField(blank=True, default=0)),
                ('beverage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.beverage')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_beverages_total', to='service.order')),
            ],
        ),
        migrations.CreateModel(
            name='MealOrderTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_amount', models.IntegerField(blank=True, default=0)),
                ('tot_qty', models.IntegerField(blank=True, default=0)),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.meal')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_meals_total', to='service.order')),
            ],
        ),
        migrations.CreateModel(
            name='TeaOrderTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_amount', models.IntegerField(blank=True, default=0)),
                ('tot_qty', models.IntegerField(blank=True, default=0)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_teas_total', to='service.order')),
                ('tea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.tea')),
            ],
        ),
    ]
