# Generated by Django 5.0.7 on 2024-11-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_beverageordertotal_mealordertotal_teaordertotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beverageordertotal',
            old_name='tot_amount',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='beverageordertotal',
            old_name='tot_qty',
            new_name='total_qty',
        ),
        migrations.RenameField(
            model_name='mealordertotal',
            old_name='tot_amount',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='mealordertotal',
            old_name='tot_qty',
            new_name='total_qty',
        ),
        migrations.RenameField(
            model_name='teaordertotal',
            old_name='tot_amount',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='teaordertotal',
            old_name='tot_qty',
            new_name='total_qty',
        ),
    ]
