# Generated by Django 5.0.7 on 2024-11-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_tot_amount_beverageordertotal_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverageorder',
            name='sold_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mealorder',
            name='sold_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teaorder',
            name='sold_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
