# Generated by Django 5.0.7 on 2024-08-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_tea_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('food_type', models.CharField(choices=[('Salad', 'Salad'), ('Soup', 'Soup'), ('Fried', 'Fried'), ('Stewed Dish', 'Stewed Dish'), ('BBQ', 'BBQ'), ('Burger', 'Burger'), ('Hot Dog', 'Hot Dog'), ('Pizza', 'Pizza'), ('Loaded Fries', 'Loaded Fries'), ('Wrap', 'Wrap'), ('Side', 'Side'), ('Family Deal', 'Family Deal'), ('Snack', 'Snack')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tea',
            name='tea_type',
            field=models.CharField(choices=[('Tea', 'Tea'), ('Coffee', 'Coffee'), ('Juice', 'Juice'), ('Smoothies', 'Smoothies')], max_length=50),
        ),
    ]
