# Generated by Django 5.0.7 on 2024-08-16 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_beverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeverageStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('purchase_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.beverage')),
            ],
        ),
    ]
