# Generated by Django 5.0.7 on 2024-08-17 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_beveragestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beveragestock',
            name='beverage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.beverage'),
        ),
    ]
